# Generated by Django 4.1 on 2023-01-05 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_rename_admin_admin_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='doctor_user',
        ),
        migrations.RemoveField(
            model_name='student',
            name='admin_student',
        ),
        migrations.DeleteModel(
            name='admin_model',
        ),
        migrations.DeleteModel(
            name='doctor',
        ),
        migrations.DeleteModel(
            name='student',
        ),
    ]
